version: 2
references:
  cache_repo: &cache_repo
    save_cache:
      key: v1-repo-{{ .Branch }}-{{ .Revision }}
      paths:
        - .

  restore_repo: &restore_repo
    restore_cache:
      key: v1-repo-{{ .Branch }}-{{ .Revision }}

  cache_bundle: &cache_bundle
    save_cache:
      key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      paths:
        - ./vendor/bundle

  restore_bundle: &restore_bundle
    restore_cache:
      key: v1-dependencies-{{ checksum "Gemfile.lock" }}

  run_tests: &run_tests
    run:
      name: run tests
      command: bundle exec rake spec

jobs:
  build:
    docker:
      - image: circleci/ruby:2.2
    working_directory: ~/pronto-blacklist
    steps:
      - checkout
      - *cache_repo
      - run: sudo apt-get update -qq && sudo apt-get install -y cmake
      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - *cache_bundle
  ruby_2.2:
    docker:
      - image: circleci/ruby:2.2
    working_directory: ~/pronto-blacklist
    steps:
      - *restore_repo
      - *restore_bundle
      - *run_tests
  ruby_2.3:
    docker:
      - image: circleci/ruby:2.3
    working_directory: ~/pronto-blacklist
    steps:
      - *restore_repo
      - *restore_bundle
      - *run_tests
  ruby_2.4:
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/pronto-blacklist
    steps:
      - *restore_repo
      - *restore_bundle
      - *run_tests
  ruby_2.5:
    docker:
      - image: circleci/ruby:2.5
    working_directory: ~/pronto-blacklist
    steps:
      - *restore_repo
      - *restore_bundle
      - *run_tests

workflows:
  version: 2
  test_supported_ruby_versions:
    jobs:
      - build
      - ruby_2.2:
          requires:
            - build
      - ruby_2.3:
          requires:
            - build
      - ruby_2.4:
          requires:
            - build
      - ruby_2.5:
          requires:
            - build
